apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # List of apps
          - list:
              elements:
                - name: guestbook
                  path: guestbook
          # List of environments
          - list:
              elements:
                - env: dev
                - env: staging
                - env: prod
  template:
    metadata:
      name: '{{name}}-{{env}}'
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: applications
        environment: '{{env}}'
    spec:
      project: applications
      source:
        repoURL: https://github.com/thaddeuscleo/cleoverse-gitops.git
        targetRevision: HEAD
        path: ./workloads/applications/{{path}}/overlays/{{env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
